=== ciscoDIZ/DossierT7LND/practica15/clinicaVeterinaria.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.misitio.com" xmlns="http://www.misitio.com"
           elementFormDefault="qualified">
    <xs:element name="clinicaVeterinaria" type="tipoClinica"/>
    <xs:complexType name="tipoClinica">
        <xs:sequence>
            <xs:element name="cliente" minOccurs="0"
                        maxOccurs="unbounded" type="tipoCliente"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="tipoCliente">
        <xs:sequence>
            <xs:element name="nombre" type="xs:string"/>
            <xs:element name="apellidos" type="xs:string"/>
            <xs:element name="animal" maxOccurs="unbounded" type="tipoAnimal"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="tipoAnimal">
        <xs:sequence>
            <xs:element name="nombre" type="xs:string"/>
            <xs:element name="edad">
                <xs:simpleType>
                    <xs:restriction base="xs:positiveInteger">
                        <xs:maxInclusive value="15"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="raza" type="xs:string"/>
            <xs:element name="tipo">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="perro"/>
                        <xs:enumeration value="gato"/>
                        <xs:enumeration value="reptil"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="sexo" type="tipoSexo" default="M"/>
    </xs:complexType>
    <xs:complexType name="tipoSexo">
        <xs:simpleContent>
            <xs:restriction base="xs:string">
                <xs:enumeration value="H"/>
                <xs:enumeration value="M"/>
            </xs:restriction>
        </xs:simpleContent>
    </xs:complexType>
</xs:schema>

=== ciscoDIZ/DossierT7LND/practica15/index.xml
<?xml version="1.0" encoding="UTF-8" ?>
<clinicaVeterinaria xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="http://www.misitio.com"
        xsi:schemaLocation="http://www.misitio.com clinicaVeterinaria.xsd">
        <cliente>
                <nombre>Pedro</nombre>
                <apellidos>Picapiedra</apellidos>
                <animal sexo="H">
                        <nombre>Perro</nombre>
                        <edad>10</edad>
                        <raza>a saber</raza>
                        <tipo>perro</tipo>
                </animal>
        </cliente>
        <cliente>
                <nombre>Pedro</nombre>
                <apellidos>Picapiedra</apellidos>
                <animal sexo="H">
                        <nombre>Perro</nombre>
                        <edad>10</edad>
                        <raza>a saber</raza>
                        <tipo>perro</tipo>
                </animal>
        </cliente>
        <cliente>
                <nombre>Pedro</nombre>
                <apellidos>Picapiedra</apellidos>
                <animal sexo="H">
                        <nombre>Perro</nombre>
                        <edad>10</edad>
                        <raza>a saber</raza>
                        <tipo>perro</tipo>
                </animal>
        </cliente>
</clinicaVeterinaria>
