=== ciscoDIZ/DossierT7LND/practica09/coche.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.misitio.com" xmlns="http://www.misitio.com"
           elementFormDefault="qualified">
    <xs:element name="compra" type="remesa"/>
    <xs:element name="coche" type="datosCoche"/>
    <xs:complexType name="datosCoche">
        <xs:sequence>
            <xs:element name="marca" type="xs:string"/>
            <xs:element name="modelo" type="xs:string"/>
            <xs:element name="puertas">
                <xs:simpleType>
                    <xs:restriction base="xs:integer">
                        <xs:minInclusive value="0"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="color">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="blanco"/>
                        <xs:enumeration value="gris"/>
                        <xs:enumeration value="rojo"/>
                        <xs:enumeration value="verde"/>
                        <xs:enumeration value="azul"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="remesa">
        <xs:complexContent>
            <xs:extension base="datosCoche">
                <xs:sequence>
                    <xs:element name="numCoches" type="xs:integer"/>
                    <xs:element name="nombreBarco" type="xs:string"/>
                    <xs:element name="paisProductor" type="xs:string"/>

                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
</xs:schema>

=== ciscoDIZ/DossierT7LND/practica09/index.xml
<?xml version="1.0" encoding="UTF-8" ?>
<compra xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="http://www.misitio.com"
        xsi:schemaLocation="http://www.misitio.com coche.xsd">
        <marca>Toyota</marca>
        <modelo>Land Cruiser</modelo>
        <puertas>4</puertas>
        <color>gris</color>
        <numCoches>100</numCoches>
        <nombreBarco>Barco</nombreBarco>
        <paisProductor>Japon</paisProductor>

</compra>
